version: '3.1'

services:
  db:
    container_name: self_storage
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=self_storage
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
